# SITE CONFIGURATION
# the subpath of your site, e.g. /blog/
baseurl: ""
url: "https://darrenhaken.github.io/"
timezone: "Europe/London"

# THEME-SPECIFIC CONFIGURATION
theme_info:
  # Meta
  title: All things developer and lean
  avatar: avatar.png
  gravatar: f0ab3db26bd3b23205db53754395894a
  description: "Software developer, lean, agile, XP, devops, TDD, Kanban" # used by search engines

  # Header and footer text
  header_text: >
     <p>Technical leader, agile coach and software engineer<br>
     Interested in technical leadership, agile/lean, continuous delivery, <br> microservices and recently big data.</p>
  footer_text:

  # Icons
  rss: false
  email_address: darrenhaken@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "darrenhaken"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/darrenhaken"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  tumblr:
  twitter: "https://twitter.com/darrenhaken"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-58893620-1"
  disqus_shortname: "darren-haken-software-blog.disqus.com"

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

# Plugins  
gems: [jekyll-paginate]
