# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Darren Haken
name: "Darren Haken"
email: darrenhaken@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings about software development and technical leadership. Interested in devops, cloud, big data.
url: "https://darrenhaken.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/darren-blog" # the subpath of your site, e.g. /blog
twitter_username: darrenhaken
github_username:  darrenhaken
repository:           darrenhaken/darren-blog
teaser:               # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute:     200
comments:
  provider:           "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname:        "darren-haken-software-blog" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  # discourse:
  #   server # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid:
    num_posts:        # 5 (default)
    colorscheme:      # "light" (default), "dark"


#Social and analytic settings
twitter:
  username: "darrenhaken"
facebook:
  app_id: ""
  publisher: ""
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-1234567-8"

# Defaults for layouts
defaults:
  - scope:
      path:           ""
      type:           posts
    values:
      layout:         single
      author_profile: true
      read_time:      true
      comments:       true
      share:          true
      related:        true

# Pagination config
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Author settings
author:
  name:               "Darren Haken"
  avatar:             "/assets/images/darren_bio.jpg"
  bio:                "Technical leader, love technology and building things"
  email:              darrenhaken@gmail.com
  github:             darrenhaken
  twitter:            darrenhaken
  linkedin:           darrenhaken
  uri:                "https://www.darrenhaken.com"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
